# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161106_1229'),
        ('landing', '0002_auto_20161106_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontacts',
            name='from_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Property'),
        ),
        migrations.AlterField(
            model_name='article',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(max_length=50, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f'),
        ),
    ]
