# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20161107_1644'),
        ('landing', '0003_auto_20161107_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accommodation', models.BooleanField(default=False, verbose_name='\u0418\u043d\u0442\u0435\u0440\u0435\u0441\u0443\u0435\u0442 \u043b\u0438 \u043f\u0440\u043e\u0436\u0438\u0432\u0430\u043d\u0438\u0435')),
                ('is_investments', models.BooleanField(default=False, verbose_name='\u0418\u043d\u0442\u0435\u0440\u0435\u0441\u0443\u044e\u0442 \u043b\u0438 \u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0446\u0438\u0438')),
                ('property_type', models.CharField(choices=[('c', 'condominium'), ('t', 'townhouse'), ('v', 'villa')], max_length=2, verbose_name='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('district', models.ManyToManyField(null=True, to='catalog.District', verbose_name='\u0420\u0430\u0439\u043e\u043d')),
            ],
            options={
                'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0432\u044b\u0431\u043e\u0440\u0435',
                'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0432\u044b\u0431\u043e\u0440\u0430\u0445',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438'},
        ),
        migrations.AlterModelOptions(
            name='usercontacts',
            options={'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f', 'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='usercontacts',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='from_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Property', verbose_name='\u041d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='usercontacts',
            name='choice_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.ChoiceInfo', verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0432\u044b\u0431\u043e\u0440\u0435'),
        ),
    ]
