# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20161107_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='choice_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.ChoiceInfo', verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0432\u044b\u0431\u043e\u0440\u0435'),
        ),
    ]
