# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20161107_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='from_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Property', verbose_name='\u041d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c'),
        ),
    ]
