# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('landing', '0010_auto_20161107_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceinfo',
            options={'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0432\u044b\u0431\u043e\u0440\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f', 'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0432\u044b\u0431\u043e\u0440\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439'},
        ),
        migrations.AddField(
            model_name='choiceinfo',
            name='session_key',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
        migrations.AlterField(
            model_name='usercontacts',
            name='choice_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.ChoiceInfo', verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0432\u044b\u0431\u043e\u0440\u0435'),
        ),
    ]
