# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 21:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20161108_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('content', ckeditor.fields.RichTextField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL \u0430\u0434\u0440\u0435\u0441')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0441\u0442\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u041f\u0440\u043e\u0441\u0442\u044b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.AlterField(
            model_name='choiceinfo',
            name='property_type',
            field=models.CharField(choices=[('c', '\u041a\u043e\u043d\u0434\u043e\u043c\u0438\u043d\u0438\u0443\u043c'), ('t', '\u0422\u0430\u0443\u043d\u0445\u0430\u0443\u0441'), ('v', '\u0412\u0438\u043b\u043b\u0430')], max_length=2, verbose_name='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'),
        ),
    ]
