# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20161206_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='articles', verbose_name='\u0424\u043e\u0442\u043e'),
            preserve_default=False,
        ),
    ]
