# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 20:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_en',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='article',
            name='header_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=ckeditor.fields.RichTextField(max_length=200, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=ckeditor.fields.RichTextField(max_length=200, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
