# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 12:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20161214_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
