# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20161108_1400'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='property_types',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='targets',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='districts_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conf_districts_info', to='landing.Article', verbose_name='\u041e \u0440\u0430\u0439\u043e\u043d\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='property_types_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conf_property_types_info', to='landing.Article', verbose_name='\u041e \u0442\u0438\u043f\u0430\u0445 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='targets_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conf_targets_info', to='landing.Article', verbose_name='\u041e \u0446\u0435\u043b\u044f\u0445 \u043f\u043e\u043a\u0443\u043f\u043a\u0438'),
        ),
    ]
