# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20161109_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='euro_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='\u041a\u0443\u0440\u0441 \u0435\u0432\u0440\u043e \u043a \u0431\u0430\u0442\u0443'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='rub_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='\u041a\u0443\u0440\u0441 \u0440\u0443\u0431\u043b\u044f \u043a \u0431\u0430\u0442\u0443'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='usd_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043a \u0431\u0430\u0442\u0443'),
            preserve_default=False,
        ),
    ]
