# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20161207_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='en',
            field=models.TextField(max_length=400, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='ru',
            field=models.TextField(max_length=400, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0440\u0443\u0441\u0441\u043a\u043e\u043c'),
        ),
    ]
