# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20161208_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='en',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='ru',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='text',
            field=models.TextField(default='', max_length=400, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
            preserve_default=False,
        ),
    ]
