# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20161218_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='text_en',
            field=models.TextField(max_length=400, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='text_ru',
            field=models.TextField(max_length=400, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
