# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20161218_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header',
            field=models.CharField(default=' ', max_length=150, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_en',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
