# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20161218_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text_en',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
