# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('c', 'condominium'), ('t', 'townhouse'), ('v', 'villa')], max_length=2, verbose_name='Property type')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('distance_to_beach', models.PositiveIntegerField(verbose_name='Distance to the beach')),
                ('living_space', models.PositiveIntegerField(verbose_name='Living space')),
                ('number_of_bedrooms', models.PositiveIntegerField(verbose_name='Number of bedrooms')),
                ('additional_info', models.TextField(blank=True, max_length=200, verbose_name='Information about additional facilities')),
                ('price', models.FloatField(verbose_name='Price')),
                ('photo', models.ImageField(upload_to='catalog/self.pk', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='State')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.State'),
        ),
    ]
