# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 12:29
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u0420\u0430\u0439\u043e\u043d')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.property_directory_path, verbose_name='\u0424\u043e\u0442\u043e')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='living_space',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.AddField(
            model_name='property',
            name='space',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c'),
        ),
        migrations.AlterField(
            model_name='property',
            name='additional_info',
            field=models.TextField(blank=True, max_length=200, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u044f\u0445'),
        ),
        migrations.AlterField(
            model_name='property',
            name='distance_to_beach',
            field=models.PositiveIntegerField(verbose_name='\u0420\u0430\u0441\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u0434\u043e \u043f\u043b\u044f\u0436\u0430'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0441\u043f\u0430\u043b\u0435\u043d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('c', 'condominium'), ('t', 'townhouse'), ('v', 'villa')], max_length=2, verbose_name='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='real_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.District'),
        ),
    ]
