# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161107_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyphoto',
            old_name='real_property',
            new_name='property',
        ),
    ]
