# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20161107_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.District', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
    ]
