# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20161107_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('c', '\u041a\u043e\u043d\u0434\u043e\u043c\u0438\u043d\u0438\u0443\u043c'), ('t', '\u0422\u0430\u0443\u043d\u0445\u0430\u0443\u0441'), ('v', '\u0412\u0438\u043b\u043b\u0430')], max_length=2, verbose_name='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'),
        ),
    ]
