# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_property_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_info_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u044f\u0445'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_info_ru',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u044f\u0445'),
        ),
        migrations.AddField(
            model_name='property',
            name='district_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.District', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='property',
            name='district_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.District', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_en',
            field=models.CharField(choices=[('c', '\u041a\u043e\u043d\u0434\u043e\u043c\u0438\u043d\u0438\u0443\u043c'), ('t', '\u0422\u0430\u0443\u043d\u0445\u0430\u0443\u0441'), ('v', '\u0412\u0438\u043b\u043b\u0430')], max_length=2, null=True, verbose_name='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_ru',
            field=models.CharField(choices=[('c', '\u041a\u043e\u043d\u0434\u043e\u043c\u0438\u043d\u0438\u0443\u043c'), ('t', '\u0422\u0430\u0443\u043d\u0445\u0430\u0443\u0441'), ('v', '\u0412\u0438\u043b\u043b\u0430')], max_length=2, null=True, verbose_name='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438'),
        ),
    ]
