# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20161214_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='district_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='district_ru',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type_ru',
        ),
    ]
