# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20161218_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='end_building',
            field=models.DateField(default=django.utils.timezone.now, help_text='\u0418\u043c\u0435\u0435\u0442 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0442\u043e\u043b\u044c\u043a\u043e \u043c\u0435\u0441\u044f\u0446 \u0438 \u0433\u043e\u0434. \u0414\u0435\u043d\u044c \u043c\u043e\u0436\u043d\u043e \u0443\u043a\u0430\u0437\u0430\u0442\u044c \u043b\u044e\u0431\u043e\u0439.', verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430'),
            preserve_default=False,
        ),
    ]
