# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_property_new_resale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u044f\u0445'),
        ),
        migrations.AlterField(
            model_name='property',
            name='additional_info_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u044f\u0445'),
        ),
        migrations.AlterField(
            model_name='property',
            name='additional_info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u0441\u043e\u043e\u0440\u0443\u0436\u0435\u043d\u0438\u044f\u0445'),
        ),
        migrations.AlterField(
            model_name='property',
            name='distance_to_beach',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0420\u0430\u0441\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u0434\u043e \u043f\u043b\u044f\u0436\u0430'),
        ),
    ]
