# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20170117_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041a\u043b\u0430\u0441\u0441 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u041a\u043b\u0430\u0441\u0441\u044b \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PropertyQuality', verbose_name='\u041a\u043b\u0430\u0441\u0441'),
        ),
    ]
