# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-16 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20170516_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.District', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.PropertyQuality', verbose_name='\u041a\u043b\u0430\u0441\u0441'),
        ),
    ]
